---
configs:
  use: 'home'
  dev:
    public_ip: '192.168.2.127'

  thedr:
    private_ip: 10.55.55.27
    virtualbox:
      cpus: 4
      memory: 4096
    description: |
      Naboo (ucibox)
      =====================================================
      This virtual machine was created by Trilogy 2U
      for their University Cybersecurity Bootcamps.
                                                          =
      This VM was included in the G3 lab for convenience.
                              =
      =========
      Accounts:
          Vagrant: vagrant / splunk
          Admin:   admin / cybersecurity
                             =
      =======
      Splunk:
          Start:    g3enable nakadia
          Connect:  http://splunk.galaxy3.net:8000
          User:     admin / cybersecurity
                             =
